name: publish-release

on:
  push:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.create_tag.outputs.version }}
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install uv

      - name: get version
        id: get_version
        run: |
          version=$(python -c "ns={}; exec(open('src/mft2es/__about__.py').read(), ns); print(ns['__version__'])")
          echo "version=$version" >> "$GITHUB_ENV"
        shell: bash

      - name: run python
        run: |
          uv run mft2es -h
          uv run mft2es -v
          uv run mft2json -h
          uv run mft2json -v
      
      - name: build
        run: |
          uv run python -m nuitka --standalone --onefile --follow-imports -o mft2es-windows-x64-v$env:version.exe --output-dir=dist --assume-yes-for-downloads src/mft2es/views/Mft2esView.py
          uv run python -m nuitka --standalone --onefile --follow-imports -o mft2json-windows-x64-v$env:version.exe --output-dir=dist --assume-yes-for-downloads src/mft2es/views/Mft2jsonView.py
      
      - name: verify
        run: |
          dist/mft2es-windows-x64-v$version.exe -h
          dist/mft2es-windows-x64-v$version.exe -v
          dist/mft2json-windows-x64-v$version.exe -h
          dist/mft2json-windows-x64-v$version.exe -v
        shell: bash
      
      - name: create tag
        id: create_tag
        if: startsWith(github.ref, 'refs/heads/master')
        run: |
          version=$(python -c "ns={}; exec(open('src/mft2es/__about__.py').read(), ns); print(ns['__version__'])")
          git tag "v$version"
          git push origin "v$version"
          echo "version=$version" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.create_tag.outputs.version }}
          files: |
            dist/mft2es-windows-x64-v${{ env.version }}.exe
            dist/mft2json-windows-x64-v${{ env.version }}.exe
          name: Release v${{ steps.create_tag.outputs.version }}
          body: 'This release was automatically created by GitHub Actions.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    needs: build-windows
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.11']
    env:
      version: ${{ needs.build-windows.outputs.version }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt install patchelf
          pip install uv

      - name: run python
        run: |
          uv run mft2es -h
          uv run mft2es -v
          uv run mft2json -h
          uv run mft2json -v

      - name: build
        run: |
          pip install nuitka
          uv run python -m nuitka --standalone --onefile --follow-imports -o mft2es-linux-x64-v$version --output-dir=dist --assume-yes-for-downloads src/mft2es/views/Mft2esView.py
          uv run python -m nuitka --standalone --onefile --follow-imports -o mft2json-linux-x64-v$version --output-dir=dist --assume-yes-for-downloads src/mft2es/views/Mft2jsonView.py
      
      - name: verify
        run: |
          dist/mft2es-linux-x64-v$version -h
          dist/mft2es-linux-x64-v$version -v
          dist/mft2json-linux-x64-v$version -h
          dist/mft2json-linux-x64-v$version -v

      - name: upload asset to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.build-windows.outputs.version }}
          files: |
            dist/mft2es-linux-x64-v${{ env.version }}
            dist/mft2json-linux-x64-v${{ env.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
